#!/bin/sh
set -e

mkdir -p bin
cd bin
cp ../src/*.ml* ./
cp ../examples/*.csm* ./
cp ../tests/*.csm* ./

ocamlc -i Util.ml > Util.mli
ocamlc -c Util.mli
ocamlc -c Util.ml

ocamlc -i ConfSolve.ml > ConfSolve.mli
ocamlc -c ConfSolve.mli
ocamlc -c ConfSolve.ml

ocamlyacc -v Parser.mly
ocamlc -c Parser.mli
ocamlc -c Parser.ml

ocamllex -q Lexer.mll
ocamlc -c Lexer.ml

ocamlc -c Debug.mli
ocamlc -c Debug.ml

ocamlc -i State.ml > State.mli
ocamlc -c State.mli
ocamlc -c State.ml

ocamlc -i Binding.ml > Binding.mli
ocamlc -c Binding.mli
ocamlc -c Binding.ml

ocamlc -c Counting.mli
ocamlc -c Counting.ml

ocamlc -c Forward.mli
ocamlc -c Forward.ml

ocamlc -c TypeCheck.mli
ocamlc -c TypeCheck.ml

ocamlc -c Literals.mli
ocamlc -c Literals.ml

ocamlc -c MiniZinc.mli
ocamlc -c MiniZinc.ml

ocamlc -c Csm2Mzn.ml

ocamlc -o csm2mzn Util.cmo ConfSolve.cmo Debug.cmo Parser.cmo Lexer.cmo State.cmo Binding.cmo Counting.cmo Forward.cmo TypeCheck.cmo Literals.cmo MiniZinc.cmo Csm2Mzn.cmo

#############

ocamlc -i SznSolution.ml > SznSolution.mli
ocamlc -c SznSolution.mli
ocamlc -c SznSolution.ml

ocamlc -c CSON.mli
ocamlc -c CSON.ml

ocamlyacc -v SznParser.mly
ocamlc -c SznParser.mli
ocamlc -c SznParser.ml

ocamllex -q SznLexer.mll
ocamlc -c SznLexer.ml

ocamlc -c Szn2Cson.ml

ocamlc -o szn2cson Util.cmo ConfSolve.cmo Debug.cmo Parser.cmo Lexer.cmo State.cmo Binding.cmo Counting.cmo Forward.cmo TypeCheck.cmo Literals.cmo CSON.cmo SznSolution.cmo SznParser.cmo SznLexer.cmo Szn2Cson.cmo

#############

rm *.ml*