#!/bin/sh
set -e

mkdir -p bin
cd bin
cp ../src/*.ml* ./
cp ../examples/*.csm* ./
cp ../tests/*.csm* ./

ocamlc -i ConfSolve.ml > ConfSolve.mli
ocamlc -c ConfSolve.mli
ocamlc -c ConfSolve.ml

ocamlyacc -v Parser.mly
ocamlc -c Parser.mli
ocamlc -c Parser.ml

ocamllex -q Lexer.mll
ocamlc -c Lexer.ml

ocamlc -c Debug.mli
ocamlc -c Debug.ml

ocamlc -i State.ml > State.mli
ocamlc -c State.mli
ocamlc -c State.ml

ocamlc -i Binding.ml > Binding.mli
ocamlc -c Binding.mli
ocamlc -c Binding.ml

ocamlc -c Counting.mli
ocamlc -c Counting.ml

ocamlc -c Forward.mli
ocamlc -c Forward.ml

ocamlc -c MiniZinc.mli
ocamlc -c MiniZinc.ml

ocamlc -c Csm2Mzn.ml

ocamlopt -o confsolve-semantics-native ConfSolve.ml Debug.ml Parser.ml Lexer.ml State.ml Binding.ml Counting.ml Forward.ml MiniZinc.ml Csm2Mzn.ml

strip confsolve-semantics-native

rm *.ml*