#!/bin/sh
set -e

mkdir -p bin
cd bin
cp ../src/*.ml* ./
cp ../examples/*.csm* ./
cp ../tests/*.csm* ./

echo "let sha =\n  \"`git rev-parse --short=10 HEAD`\"" > Version.ml
ocamlc -g -i Version.ml > Version.mli
ocamlc -g -c Version.mli
ocamlc -g -c Version.ml

ocamlc -g -i Util.ml > Util.mli
ocamlc -g -c Util.mli
ocamlc -g -c Util.ml

ocamlc -g -i ConfSolve.ml > ConfSolve.mli
ocamlc -g -c ConfSolve.mli
ocamlc -g -c ConfSolve.ml

ocamlyacc -v Parser.mly
ocamlc -g -c Parser.mli
ocamlc -g -c Parser.ml

ocamllex -q Lexer.mll
ocamlc -g -c Lexer.ml

ocamlc -g -c Debug.mli
ocamlc -g -c Debug.ml

ocamlc -g -i State.ml > State.mli
ocamlc -g -c State.mli
ocamlc -g -c State.ml

ocamlc -g -i Binding.ml > Binding.mli
ocamlc -g -c Binding.mli
ocamlc -g -c Binding.ml

ocamlc -g -c Counting.mli
ocamlc -g -c Counting.ml

ocamlc -g -c Forward.mli
ocamlc -g -c Forward.ml

ocamlc -g -c TypeCheck.mli
ocamlc -g -c TypeCheck.ml

ocamlc -g -c Literals.mli
ocamlc -g -c Literals.ml

ocamlc -g -c MiniZinc.mli
ocamlc -g -c MiniZinc.ml

ocamlc -g -c Csm2Mzn.ml

ocamlc -g -o csm2mzn Version.cmo Util.cmo ConfSolve.cmo Debug.cmo Parser.cmo Lexer.cmo State.cmo Binding.cmo Counting.cmo Forward.cmo TypeCheck.cmo Literals.cmo MiniZinc.cmo Csm2Mzn.cmo

#############

ocamlc -g -i SznSolution.ml > SznSolution.mli
ocamlc -g -c SznSolution.mli
ocamlc -g -c SznSolution.ml

ocamlc -g -c CSON.mli
ocamlc -g -c CSON.ml

ocamlyacc -v SznParser.mly
ocamlc -g -c SznParser.mli
ocamlc -g -c SznParser.ml

ocamllex -q SznLexer.mll
ocamlc -g -c SznLexer.ml

ocamlc -g -c Szn2Cson.ml

ocamlc -g -o szn2cson Version.cmo Util.cmo ConfSolve.cmo Debug.cmo Parser.cmo Lexer.cmo State.cmo Binding.cmo Counting.cmo Forward.cmo TypeCheck.cmo Literals.cmo CSON.cmo SznSolution.cmo SznParser.cmo SznLexer.cmo Szn2Cson.cmo

#############

rm *.ml*