#!/bin/sh
set -e

mkdir -p bin
cd bin
cp ../src/*.ml* ./
cp ../examples/*.spec* ./
cp ../tests/*.spec* ./

ocamlc -i ConfSolve.ml > ConfSolve.mli
ocamlc -c ConfSolve.mli
ocamlc -c ConfSolve.ml

ocamlyacc -v Parser.mly
ocamlc -c Parser.mli
ocamlc -c Parser.ml

ocamllex -q Lexer.mll
ocamlc -c Lexer.ml

ocamlc -c Debug.mli
ocamlc -c Debug.ml

ocamlc -i State.ml > State.mli
ocamlc -c State.mli
ocamlc -c State.ml

ocamlc -i Binding.ml > Binding.mli
ocamlc -c Binding.mli
ocamlc -c Binding.ml

ocamlc -c Counting.mli
ocamlc -c Counting.ml

ocamlc -c Forward.mli
ocamlc -c Forward.ml

ocamlc -c MiniZinc.mli
ocamlc -c MiniZinc.ml

ocamlc -c Program.ml

ocamlc -o confsolve-semantics-bytecode ConfSolve.cmo Debug.cmo Parser.cmo Lexer.cmo State.cmo Binding.cmo Counting.cmo Forward.cmo MiniZinc.cmo Program.cmo

rm *.ml*

./confsolve-semantics-bytecode $*