#!/bin/sh
set -e

mkdir -p bin
cd bin
cp ../src/*.ml* ./
cp ../examples/*.csm* ./
cp ../tests/*.csm* ./

ocamlc -g -i ConfSolve.ml > ConfSolve.mli
ocamlc -g -c ConfSolve.mli
ocamlc -g -c ConfSolve.ml

ocamlyacc -v Parser.mly
ocamlc -g -c Parser.mli
ocamlc -g -c Parser.ml

ocamllex -q Lexer.mll
ocamlc -g -c Lexer.ml

ocamlc -g -c Debug.mli
ocamlc -g -c Debug.ml

ocamlc -g -i State.ml > State.mli
ocamlc -g -c State.mli
ocamlc -g -c State.ml

ocamlc -g -i Binding.ml > Binding.mli
ocamlc -g -c Binding.mli
ocamlc -g -c Binding.ml

ocamlc -g -c Counting.mli
ocamlc -g -c Counting.ml

ocamlc -g -c Forward.mli
ocamlc -g -c Forward.ml

ocamlc -g -c MiniZinc.mli
ocamlc -g -c MiniZinc.ml

ocamlc -g -c Csm2Mzn.ml

ocamlc -g -o confsolve-semantics-bytecode ConfSolve.cmo Debug.cmo Parser.cmo Lexer.cmo State.cmo Binding.cmo Counting.cmo Forward.cmo MiniZinc.cmo Csm2Mzn.cmo

rm *.ml*

OCAMLRUNPARAM='b'
ocamlrun -b ./confsolve-semantics-bytecode $*