#!/bin/sh
cd bin
rm temp.mzn
echo "csm2mzn..."
./csm2mzn $* > temp.mzn
echo "mzn2fzn..."
mzn2fzn --no-optimize --no-output-ozn temp.mzn
echo "fz..."
fz -time 60000 -s temp.fzn > temp.szn
echo "szn2cson..."
./szn2cson $2 temp.szn