#!/bin/bash
cd tests
rm -r -f temp
mkdir -p temp
cd temp

function run {
  for f in $1
  do
    result="PASS"
    base=`basename $f`
    
    if [ -e ${f%.*}.params ]; then
      ../../bin/csm2mzn $f -p ${f%.*}.params &> ${base%.*}.mzn
    else
      ../../bin/csm2mzn $f &> ${base%.*}.mzn
    fi

    if [ $? -ne 0 ]; then
      result="FAIL--EXIT"
    else
      # compare output (mzn)
      #if diff ${base%.*}.mzn ../mzn/${base%.*}.mzn &> /dev/null; then
      #  nonsense=""
      #else
      #  result="FAIL--MZN"
      #fi
      
      # minizinc
      if mzn2fzn --no-optimize ${base%.*}.mzn &> /dev/null; then
        
        # solve
        if fz -time 3000 ${base%.*}.fzn &> ${base%.*}.szn; then
          
          # generate CSON
          solns2out ${base%.*}.ozn ${base%.*}.szn -o ${base%.*}-out.szn

          if ../../bin/szn2cson $f ${base%.*}-out.szn &> ${base%.*}.cson; then
             
             nonsense=""
             # TODO: parse the CSON back in again... ?
             #if ../../bin/csm2mzn $f -s ${base%.*}.cson &> ${base%.*}-cson.mzn; then
             #  nonsense=""
             #else
             #  result="FAIL--CSM2MZN-CSON"
             #fi
             
          else
            result="FAIL--SZN2CSON"
          fi
          
        else
          result="FAIL--SOLVE"
        fi
        
      else
        result="FAIL--MZN2FZN"
      fi
      
    fi

    if [ $result = "PASS" ]; then
      printf "%-30s%-15s\n" ${base%.*} $result
    else
      printf "\x1b\x5b1;31;40m%-30s%-15s\n\x1b\x5b0;37;40m" ${base%.*} $result
    fi

  done
}

run "../*.csm"
run "../../examples/*.csm"