#!/bin/bash
cd tests
rm -r -f temp
mkdir -p temp
cd temp

function run {
  for f in $1
  do
    base=`basename $f`
    ../../bin/csm2mzn $f &> ${base%.*}.mzn

    if [ $? -ne 0 ]; then
      result="FAIL--EXIT"
    else
      result="PASS"
    fi

    if [ $result = "PASS" ]; then
      printf "%-30s%-15s\n" ${base%.*} $result
    else
      printf "\x1b\x5b1;31;40m%-30s%-15s\n\x1b\x5b0;37;40m" ${base%.*} $result
    fi

  done
}

run "../*.csm"
run "../../examples/*.csm"